### ISSUE TITLE
[BUG] template-arb-file not compatible with arb-dir

### ISSUE THREAD

**Issue by frederikstonge** [google/arb-editor#50]
## Expected Behavior

template-arb-file should take arb-dir into account

## Actual Behavior

template-arb-file doesn't take arb-dir into account.

## Steps to Reproduce the Problem

```yaml
arb-dir: lib/l10n
template-arb-file: lib/l10n/app_en.arb # Will provide intellisense but will throw error : The 'template-arb-file', LocalFile: '**/lib/l10n/lib/l10n/app_en.arb', does not exist.
template-arb-file: app_en.arb # Won't provide intellisense but no error will be thrown.
```
